[keyboard]
name = "JL BOX"
product_name = "JL BOX"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "haobo"
chip = "nrf52840"

[matrix]
# Row and col pins are mandatory
row_pins = ["P0_02", "P0_30", "P0_00", "P1_09", "P0_01"]
col_pins = ["P1_11", "P1_10", "P0_03", "P0_28", "P1_13"]
# RMK uses col2row as the default matrix diode direction, if you want to use a row2col matrix, add `row2col = true`
# row2col = true

[layout]
rows = 5
cols = 5
layers = 16
matrix_map = """
(0,0) (0,1) (0,2) (0,3) (0,4)
(1,0) (1,1) (1,2) (1,3) (1,4)
(2,0) (2,1) (2,2) (2,3) (2,4)
(3,0) (3,1) (3,2) (3,3) (3,4)
(4,0) (4,1) (4,2) (4,3) (4,4)
"""

[[layer]]
name = "base_layer"
keys = """
Kc1 Kc2 Kc3 Kc4 Kc5
Kc1 Kc2 Kc3 Kc4 Kc5
Kc1 Kc2 Kc3 Kc4 Kc5
Kc1 Kc2 Kc3 Kc4 Kc5
Kc1 Kc2 Kc3 Kc4 Kc5
"""
# Encoder 0 - CW: AudioVolUp, CCW: AudioVolDown
encoders = [["AudioVolUp", "AudioVolDown"]]

[[layer]]
name = "second_layer"
keys = """
Kc1 Kc2 Kc3 Kc4 Kc5
Kc1 Kc2 Kc3 Kc4 Kc5
Kc1 Kc2 Kc3 Kc4 Kc5
Kc1 Kc2 Kc3 Kc4 Kc5
Kc1 Kc2 Kc3 Kc4 Kc5
"""
# Encoder 0 - CW: BrightnessUp, CCW: BrightnessDown
encoders = [["BrightnessUp", "BrightnessDown"]]

[aliases]
my_copy = "WM(C, LCtrl)"
my_paste = "WM(V, LCtrl)"

[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
# capslock.pin = "P0_30"
# capslock.low_active = false
# scrolllock.pin = "PA3"
# scrolllock.low_active = true
# Just ignore if no light pin is used for it
# numslock.pin = "PA5"
# numslock.low_active = true

[[input_device.encoder]]
pin_a = "P0_10"
pin_b = "P0_09"
phase = "resolution"
internal_pullup = true
resolution = 4
reverse = false
# Encoder 0
[[input_device.encoder]]
pin_a = "P0_24"
pin_b = "P0_13"
phase = "resolution"
internal_pullup = true
resolution = 4
reverse = false
# Encoder 1
[[input_device.encoder]]
pin_a = "P0_17"
pin_b = "P0_15"
phase = "resolution"
internal_pullup = true
resolution = 4
reverse = false
# Encoder 2
[[input_device.encoder]]
pin_a = "P0_06"
pin_b = "P0_26"
phase = "resolution"
internal_pullup = true
resolution = 2
reverse = false
# Encoder 3
[[input_device.encoder]]
pin_a = "P0_31"
pin_b = "P0_29"
phase = "resolution"
internal_pullup = true
resolution = 4
reverse = false
# Encoder 4

[storage]
# Storage feature is enabled by default
# enabled = false
# clear_storage = true

[ble]
enabled = true
# vddh has an internal voltage divider
battery_adc_pin = "vddh"
# Or
# battery_adc_pin = "P0_04"
# adc_divider_measured = 2000
# adc_divider_total = 2806

[rmk]
combo_max_num = 128
fork_max_num = 16
macro_space_size = 2048

# IGNORE/DONT-INCLUDE THIS SECTION Unless you're using custom nRF52840 based board (Eg not a nice!nano)
[chip.nrf52840]
# DCDC regulator 0 enabled (default: true)
dcdc_reg0 = true
# DCDC regulator 1 enabled (default: true)
dcdc_reg1 = true
# DCDC regulator 0 voltage: "3V3" or "1V8" (default: "3V3")
dcdc_reg0_voltage = "3V3"
